const s = (es, en, fr, eu) => ({ es, en, fr, eu });

export const STRINGS = {
  nav_dashboard: s("Panel", "Dashboard", "Tableau de bord", "Panela"),
  nav_problems: s("Tipos de problema", "Problem types", "Types de problème", "Arazo motak"),
  nav_questionnaires: s("Cuestionarios", "Questionnaires", "Questionnaires", "Galdetegiak"),
  nav_tasks: s("Tareas", "Tasks", "Tâches", "Zereginak"),
  nav_home: s("Inicio", "Home", "Accueil", "Hasiera"),
  nav_notes: s("Mis notas", "My notes", "Mes notes", "Nire oharrak"),
  logout: s("Cerrar sesión", "Log out", "Se déconnecter", "Saioa itxi"),
  hello: s("Hola", "Hello", "Bonjour", "Kaixo"),
  patient_home_sub: s(
    "Estas son las tareas que tu profesional ha preparado para ti.",
    "These are the tasks your clinician has prepared for you.",
    "Voici les tâches que votre thérapeute a préparées pour vous.",
    "Hauek dira zure profesionalak zuretzat prestatu dituen zereginak."
  ),
  my_tasks: s("Mis tareas", "My tasks", "Mes tâches", "Nire zereginak"),
  no_tasks: s("Todavía no tienes tareas asignadas.", "You don't have any assigned tasks yet.", "Vous n'avez pas encore de tâches assignées.", "Oraindik ez duzu zereginik esleituta."),
  complete_now: s("Completar ahora", "Complete now", "Compléter maintenant", "Orain bete"),
  add_notes: s("Añadir notas", "Add notes", "Ajouter des notes", "Oharrak gehitu"),
  freq_once: s("Una vez", "Once", "Une fois", "Behin"),
  freq_daily: s("Diaria", "Daily", "Quotidienne", "Egunero"),
  freq_weekly: s("Semanal", "Weekly", "Hebdomadaire", "Astero"),
  freq_custom: s("Personalizada", "Custom", "Personnalisée", "Pertsonalizatua"),
  type_questionnaire: s("Cuestionario", "Questionnaire", "Questionnaire", "Galdetegia"),
  type_note_prompt: s("Notas de sensaciones", "Sensation notes", "Notes de sensations", "Sentsazio-oharrak"),
  type_module: s("Módulo", "Module", "Module", "Modulua"),
  type_custom: s("Personalizada", "Custom", "Personnalisée", "Pertsonalizatua"),
  status_active: s("Activa", "Active", "Active", "Aktiboa"),
  status_paused: s("Pausada", "Paused", "En pause", "Etenda"),
  status_completed: s("Completada", "Completed", "Terminée", "Osatua"),
  status_archived: s("Archivada", "Archived", "Archivée", "Artxibatua"),
  why: s("Motivo", "Reason", "Motif", "Arrazoia"),
  last_done: s("Última vez", "Last completed", "Dernière fois", "Azken aldiz"),
  never: s("Nunca", "Never", "Jamais", "Inoiz ez"),
  submit: s("Enviar", "Submit", "Envoyer", "Bidali"),
  save: s("Guardar", "Save", "Enregistrer", "Gorde"),
  cancel: s("Cancelar", "Cancel", "Annuler", "Utzi"),
  delete: s("Eliminar", "Delete", "Supprimer", "Ezabatu"),
  confirm_delete: s("¿Seguro que quieres eliminarlo?", "Are you sure you want to delete it?", "Voulez-vous vraiment le supprimer ?", "Ziur ezabatu nahi duzula?"),
  back: s("Volver", "Back", "Retour", "Itzuli"),
  thanks_title: s("Gracias por compartirlo", "Thank you for sharing", "Merci pour votre partage", "Eskerrik asko partekatzeagatik"),
  thanks_sub: s(
    "Tus respuestas se han guardado. Tu profesional podrá revisarlas.",
    "Your answers have been saved. Your clinician will be able to review them.",
    "Vos réponses ont été enregistrées. Votre thérapeute pourra les consulter.",
    "Zure erantzunak gorde dira. Zure profesionalak berrikusi ahal izango ditu."
  ),
  back_home: s("Volver al inicio", "Back to home", "Retour à l'accueil", "Hasierara itzuli"),
  not_allowed: s("Este cuestionario no está asignado a ti.", "This questionnaire is not assigned to you.", "Ce questionnaire ne vous est pas assigné.", "Galdetegi hau ez dago zuri esleituta."),
  answer_all: s("Responde todas las preguntas de escala para continuar.", "Answer all scale questions to continue.", "Répondez à toutes les questions à échelle pour continuer.", "Erantzun eskala-galdera guztiei jarraitzeko."),
  your_answer: s("Tu respuesta…", "Your answer…", "Votre réponse…", "Zure erantzuna…"),
  notes_sub: s("Describe cómo te sientes, con tus propias palabras.", "Describe how you feel, in your own words.", "Décrivez ce que vous ressentez, avec vos propres mots.", "Deskribatu nola sentitzen zaren, zure hitzekin."),
  general: s("General", "General", "Général", "Orokorra"),
  note_placeholder: s("¿Qué sensaciones notas ahora mismo?", "What sensations do you notice right now?", "Quelles sensations remarquez-vous en ce moment ?", "Zer sentsazio nabaritzen dituzu orain?"),
  save_note: s("Guardar nota", "Save note", "Enregistrer la note", "Oharra gorde"),
  no_notes: s("Aún no hay notas.", "No notes yet.", "Pas encore de notes.", "Oraindik ez dago oharrik."),
  patients: s("Pacientes", "Patients", "Patients", "Pazienteak"),
  invite_patient: s("Invitar paciente", "Invite patient", "Inviter un patient", "Pazientea gonbidatu"),
  invite_sub: s(
    "Recibirá un email con un enlace para crear su cuenta.",
    "They'll receive an email with a link to create their account.",
    "Il recevra un e-mail avec un lien pour créer son compte.",
    "Posta elektroniko bat jasoko du bere kontua sortzeko esteka batekin."
  ),
  email: s("Email", "Email", "E-mail", "Posta elektronikoa"),
  send_invite: s("Enviar invitación", "Send invitation", "Envoyer l'invitation", "Gonbidapena bidali"),
  invite_sent: s("Invitación enviada a", "Invitation sent to", "Invitation envoyée à", "Gonbidapena bidalita:"),
  no_patients: s("Aún no hay pacientes. Invita al primero.", "No patients yet. Invite your first one.", "Pas encore de patients. Invitez le premier.", "Oraindik ez dago pazienterik. Gonbidatu lehena."),
  recent_activity: s("Actividad reciente", "Recent activity", "Activité récente", "Azken jarduera"),
  no_activity: s("Sin actividad todavía.", "No activity yet.", "Aucune activité pour l'instant.", "Oraindik ez dago jarduerarik."),
  completed_q: s("completó", "completed", "a complété", "bete du"),
  wrote_note: s("escribió una nota", "wrote a note", "a écrit une note", "ohar bat idatzi du"),
  active_tasks: s("activas", "active", "actives", "aktibo"),
  search: s("Buscar…", "Search…", "Rechercher…", "Bilatu…"),
  profile: s("Perfil", "Profile", "Profil", "Profila"),
  activity: s("Respuestas y notas", "Submissions & notes", "Réponses et notes", "Erantzunak eta oharrak"),
  prescribed: s("Tareas prescritas", "Prescribed tasks", "Tâches prescrites", "Agindutako zereginak"),
  language: s("Idioma", "Language", "Langue", "Hizkuntza"),
  joined: s("Alta", "Joined", "Inscrit le", "Alta"),
  assign_task: s("Asignar tarea", "Assign task", "Assigner une tâche", "Zeregina esleitu"),
  task: s("Tarea", "Task", "Tâche", "Zeregina"),
  status: s("Estado", "Status", "Statut", "Egoera"),
  start_date: s("Inicio", "Start date", "Date de début", "Hasiera-data"),
  end_date: s("Fin", "End date", "Date de fin", "Amaiera-data"),
  frequency: s("Frecuencia", "Frequency", "Fréquence", "Maiztasuna"),
  clinician_notes: s("Notas del profesional", "Clinician notes", "Notes du thérapeute", "Profesionalaren oharrak"),
  pause: s("Pausar", "Pause", "Mettre en pause", "Eten"),
  resume: s("Reanudar", "Resume", "Reprendre", "Berrekin"),
  archive: s("Archivar", "Archive", "Archiver", "Artxibatu"),
  no_assignments: s("Sin tareas asignadas.", "No assigned tasks.", "Aucune tâche assignée.", "Ez dago esleitutako zereginik."),
  submissions: s("Cuestionarios respondidos", "Completed questionnaires", "Questionnaires complétés", "Betetako galdetegiak"),
  score: s("Puntuación", "Score", "Score", "Puntuazioa"),
  problem_type: s("Tipo de problema", "Problem type", "Type de problème", "Arazo mota"),
  new_problem_type: s("Nuevo tipo", "New type", "Nouveau type", "Mota berria"),
  name: s("Nombre", "Name", "Nom", "Izena"),
  slug: s("Identificador", "Identifier", "Identifiant", "Identifikatzailea"),
  active: s("Activo", "Active", "Actif", "Aktiboa"),
  inactive: s("Inactivo", "Inactive", "Inactif", "Ez-aktiboa"),
  title: s("Título", "Title", "Titre", "Izenburua"),
  description: s("Descripción", "Description", "Description", "Deskribapena"),
  new_questionnaire: s("Nuevo cuestionario", "New questionnaire", "Nouveau questionnaire", "Galdetegi berria"),
  questions: s("Preguntas", "Questions", "Questions", "Galderak"),
  add_question: s("Añadir pregunta", "Add question", "Ajouter une question", "Galdera gehitu"),
  question_text: s("Texto de la pregunta", "Question text", "Texte de la question", "Galderaren testua"),
  question_type: s("Tipo de respuesta", "Answer type", "Type de réponse", "Erantzun mota"),
  likert: s("Escala", "Scale", "Échelle", "Eskala"),
  text_answer: s("Texto libre", "Free text", "Texte libre", "Testu librea"),
  scale_labels: s("Etiquetas de escala", "Scale labels", "Libellés d'échelle", "Eskala-etiketak"),
  labels_hint: s("Ej.: 1=Nada, 3=Algo, 5=Mucho", "E.g. 1=Not at all, 3=Somewhat, 5=Very much", "Ex. : 1=Pas du tout, 3=Un peu, 5=Beaucoup", "Adib.: 1=Batere ez, 3=Zertxobait, 5=Asko"),
  min: s("Mín", "Min", "Min", "Min"),
  max: s("Máx", "Max", "Max", "Max"),
  all: s("Todos", "All", "Tous", "Guztiak"),
  new_task: s("Nueva tarea", "New task", "Nouvelle tâche", "Zeregin berria"),
  task_type: s("Tipo de tarea", "Task type", "Type de tâche", "Zeregin mota"),
  linked_questionnaire: s("Cuestionario vinculado", "Linked questionnaire", "Questionnaire lié", "Lotutako galdetegia"),
  linked_problem: s("Tipo de problema vinculado", "Linked problem type", "Type de problème lié", "Lotutako arazo mota"),
  none: s("Ninguno", "None", "Aucun", "Bat ere ez"),
  empty_list: s("Nada por aquí todavía.", "Nothing here yet.", "Rien ici pour l'instant.", "Oraindik ez dago ezer hemen."),
  questions_count: s("preguntas", "questions", "questions", "galdera"),
  clinician_space: s("Espacio profesional", "Clinician space", "Espace thérapeute", "Profesionalaren gunea"),
  library: s("Biblioteca", "Library", "Bibliothèque", "Liburutegia"),
  patient: s("Paciente", "Patient", "Patient", "Pazientea"),
  not_found: s("No encontrado", "Not found", "Introuvable", "Ez da aurkitu"),
  module_hint: s("Sigue las indicaciones de tu profesional.", "Follow your clinician's instructions.", "Suivez les indications de votre thérapeute.", "Jarraitu zure profesionalaren jarraibideei."),
  translations_hint: s(
    "El español es obligatorio; los demás idiomas usan el español si están vacíos.",
    "Spanish is required; other languages fall back to Spanish when empty.",
    "L'espagnol est obligatoire ; les autres langues utilisent l'espagnol si vides.",
    "Gaztelania derrigorrezkoa da; beste hizkuntzek gaztelania erabiliko dute hutsik badaude."
  ),
};